### ISSUE TITLE
Model on Track 2

### ISSUE THREAD

**Issue by LiquidAmmonia** [WangLiwen1994/DeepRelight#1]
Hi! Great work and congratulations!
I noticed that your team also won the first price in Track 2(Illumination settings estimation), but I failed to find your code on Github. Could you tell me how I could find your code?

**Comment by WangLiwen1994** [comment]
Hello. We only joined the first track (any to one) of the relighting challenge. You may find the information (of track 2) from the challenge paper.

**Comment by LiquidAmmonia** [comment]
Got it. 
Thank you for your response.
